// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!

export interface PossibleTypesResultData {
	possibleTypes: {
		[key: string]: string[];
	};
}
const result: PossibleTypesResultData = {
	possibleTypes: {
		Account: ['DistributionList', 'User'],
		Node: ['File', 'Folder'],
		SharedTarget: ['DistributionList', 'User']
	}
};
export default result;
